# Generated by Django 3.2.25 on 2025-02-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Anı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Anı')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Okundu')),
                ('content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Anı')),
            ],
        ),
        migrations.CreateModel(
            name='ReadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now_add=True, verbose_name='Okuma Anı')),
            ],
        ),
    ]
