# Generated by Django 3.2.25 on 2025-02-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_written', to=settings.AUTH_USER_MODEL, verbose_name='Yazan'),
        ),
        migrations.AddField(
            model_name='message',
            name='readlist',
            field=models.ManyToManyField(related_name='message_reads', to='chat.ReadInfo', verbose_name='Okuyanlar'),
        ),
        migrations.AddField(
            model_name='chat',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chat_members', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler'),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='message_chat', to='chat.Message', verbose_name='Mesajlar'),
        ),
        migrations.AddField(
            model_name='chat',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chats_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
    ]
