# Generated by Django 3.2.25 on 2025-02-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('filestack', 'Dosya Ekleri'), ('revisestack', 'Revizeler'), ('reportstack', 'Raporlar'), ('task', 'Görevler'), ('chat', 'Sohbetler'), ('customuser', 'Kullanıcılar'), ('auths', 'Yetkilendirmeler')], max_length=30)),
                ('view', models.BooleanField(verbose_name='Görüntüleme')),
                ('add', models.BooleanField(verbose_name='Ekleme')),
                ('change', models.BooleanField(verbose_name='Düzenleme')),
                ('delete', models.BooleanField(verbose_name='Silme')),
            ],
        ),
        migrations.CreateModel(
            name='Auths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grup')),
                ('perms', models.ManyToManyField(to='auths.Perm', verbose_name='Yetkiler')),
            ],
        ),
    ]
